---
# Custom AI Library Configuration Example
tools:
  max_file_size: 5242880  # 5MB instead of default 10MB
  code_execution_timeout: 15  # 15 seconds instead of default 30
  web_request_timeout: 5  # 5 seconds instead of default 10
  math_max_iterations: 500

backends:
  cloud:
    timeout: 45  # 45 seconds instead of default 30
    max_retries: 5
  local:
    timeout: 90
    base_url: "http://localhost:11434"

chat:
  max_history_length: 50
  auto_save: false

logging:
  level: "DEBUG"